services:
  - type: worker
    name: maythusharmusicvv1
    env: python
    plan: pro plus
    region: singapore
    buildCommand: pip3 install --no-cache-dir --upgrade --requirement requirements.txt
    startCommand: bash start
    envVars:
      - key: API_ID
        value: "20078321"
      - key: API_HASH
        value: "c8ed904e4aac83cea1f27b73984debad"
      - key: BOT_TOKEN
        value: "7418613978:AAEKb1SAjIC8qChfifv31vK2iWGkPNe7mnQ"
      - key: MONGO_DB_URI
        value: "mongodb+srv://pyaesone:pyaesone@pyaesone.ii8wsxo.mongodb.net/?retryWrites=true&w=majority"
      - key: OWNER_ID
        value: "1318826936"
      - key: LOGGER_ID
        value: "-1002335122520"
      - key: STRING_SESSION
        value: "BQEyXvEATRCFSHbap7OEBUPBKyGDCjhk0SQC_qDVSek5VkkOb0lgp9tV5QJDn60g-bOODr8udcIDu2fXWvSF1GgDhD4WtO7Qpuctep65qcOtrHeKbLdBjIKYladqlU4oGinbCzRVEQDAobyGuYdygzTa962c0OrSsd2MePFFSOHCf6UnyPSW7XAnNX9WmMEOK220N0HoNrlmsxGhubkDI3HzjdnBydP_gEC7Aywt8OJYP23WMQhYCIRCsvFMlqTRgQTOjSDzD2ElIf65H30XZiSwRW0ELkzBCbnHPh-oNT6K515v21Qf-hafrGZmMNvM1ZVWSQC5veuie6y3FH7w773L92VBsgAAAAFeh0k2AA"
